export const name = 'dsh-session-manager';
import { readFile, writeFile, mkdir, rename } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { homedir } from 'node:os';
const file = join(process.env.DSH_HOME || join(homedir(), '.dsh'), 'profiles', 'web', 'dsh-session-manager.json');
const DEFAULT_CATEGORY = 'default';
const validColor = value => typeof value === 'string' && /^#[0-9a-fA-F]{6}$/.test(value) ? value : '';
function normalize(value){const sessions=value&&typeof value.sessions==='object'?value.sessions:{};const categories=Array.isArray(value&&value.categories)?value.categories.filter(x=>typeof x==='string'&&x.trim()):[];if(!categories.includes(DEFAULT_CATEGORY))categories.unshift(DEFAULT_CATEGORY);const styles=value&&typeof value.categoryStyles==='object'?value.categoryStyles:{};const categoryStyles={};for(const name of categories){const style=styles[name]||{};const background=validColor(style.background);const color=validColor(style.color);if(background||color)categoryStyles[name]={...(background?{background}:{}),...(color?{color}:{})};}return {sessions,categories,categoryStyles};}
async function readState(){try{return normalize(JSON.parse(await readFile(file,'utf8')));}catch{return normalize({});}}
async function saveState(state){await mkdir(dirname(file),{recursive:true});const tmp=file+'.tmp';await writeFile(tmp,JSON.stringify(normalize(state),null,2)+'\n','utf8');await rename(tmp,file);}
function json(res,status,value){res.writeHead(status,{'cache-control':'no-store','content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));}
function trusted(req){try{return !!req.headers.host&&(!req.headers.origin||new URL(req.headers.origin).host===req.headers.host);}catch{return false;}}
async function body(req){const chunks=[];for await(const c of req)chunks.push(Buffer.from(c));return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');}
function categoryName(value){return typeof value==='string'?value.trim().replace(/[\/]/g,'').slice(0,80):'';}
export function apply(ctx){ctx.inject(['webServer'],host=>{const web=host.webServer;const a=web.register({kind:'exact',path:'/dsh-session-manager/state',handler:async(req,res)=>{if(req.method!=='GET')return json(res,405,{error:'method'});json(res,200,await readState());}});const b=web.register({kind:'exact',path:'/dsh-session-manager/metadata',handler:async(req,res)=>{if(req.method!=='POST')return json(res,405,{error:'method'});if(!trusted(req))return json(res,403,{error:'untrusted origin'});try{const input=await body(req);const state=await readState();const category=categoryName(input.category);const action=input.action;if(action==='category-add'){if(!category)return json(res,400,{error:'category required'});if(!state.categories.includes(category))state.categories.push(category);}else if(action==='category-delete'){if(!category||category===DEFAULT_CATEGORY)return json(res,400,{error:'default category cannot be deleted'});state.categories=state.categories.filter(x=>x!==category);delete state.categoryStyles[category];for(const id of Object.keys(state.sessions))if(state.sessions[id].category===category)state.sessions[id]={...state.sessions[id],category:''};}else if(action==='category-style'){if(!category||!state.categories.includes(category))return json(res,400,{error:'category not found'});const background=validColor(input.background);const color=validColor(input.color);state.categoryStyles[category]={...(background?{background}:{}),...(color?{color}:{})};}else if(action==='categorize'){const ids=Array.isArray(input.ids)?input.ids.filter(x=>typeof x==='string'&&x.length<300):[];if(!category)return json(res,400,{error:'category required'});if(!state.categories.includes(category))state.categories.push(category);for(const id of ids)state.sessions[id]={...(state.sessions[id]||{}),category};}else return json(res,400,{error:'unknown action'});await saveState(state);json(res,200,{ok:true,state});}catch(e){json(res,400,{error:String(e)});}}});return()=>{a();b();};});}
