export const name = 'dsh-session-manager';
import { readFile, writeFile, mkdir, rename } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { homedir } from 'node:os';
const file = join(process.env.DSH_HOME || join(homedir(), '.dsh'), 'profiles', 'web', 'dsh-session-manager.json');
async function readState(){ try { const x=JSON.parse(await readFile(file,'utf8')); const categories=Array.isArray(x.categories)&&x.categories.length?x.categories:['default']; return {sessions:x.sessions&&typeof x.sessions==='object'?x.sessions:{},categories}; } catch { return {sessions:{},categories:['default']}; } }
async function saveState(state){ await mkdir(dirname(file),{recursive:true}); const tmp=file+'.tmp'; await writeFile(tmp,JSON.stringify(state,null,2)+'\n','utf8'); await rename(tmp,file); }
function json(res,status,value){res.writeHead(status,{'cache-control':'no-store','content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));}
function trusted(req){try{if(!req.headers.host)return false;return !req.headers.origin||new URL(req.headers.origin).host===req.headers.host;}catch{return false;}}
async function body(req){const chunks=[];for await(const c of req)chunks.push(Buffer.from(c));return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');}
export function apply(ctx){ ctx.inject(['webServer'], host=>{ const web=host.webServer; const a=web.register({kind:'exact',path:'/dsh-session-manager/state',handler:async(req,res)=>{if(req.method!=='GET'){res.writeHead(405);return res.end();}json(res,200,await readState());}}); const b=web.register({kind:'exact',path:'/dsh-session-manager/metadata',handler:async(req,res)=>{if(req.method!=='POST'){res.writeHead(405);return res.end();}if(!trusted(req))return json(res,403,{error:'untrusted origin'});try{const input=await body(req);const state=await readState();const ids=Array.isArray(input.ids)?input.ids.filter(x=>typeof x==='string'&&x.length<300):[];const category=typeof input.category==='string'?input.category.trim().replace(/[\/]/g,'').slice(0,80):'';if(input.action==='categorize'&&!category)return json(res,400,{error:'category required'});if(category&&!state.categories.includes(category))state.categories.push(category);for(const id of ids){const old=state.sessions[id]||{};state.sessions[id]={...old,category:input.action==='categorize'?category:(old.category||'')};}await saveState(state);json(res,200,{ok:true,state});}catch(e){json(res,400,{error:String(e)});}}});return()=>{a();b();}; });}
